version: "2"

services:
  nexus:
    image: sonatype/nexus3
    volumes:
      - nexus_data:/nexus-data
      - nexus_data:/sonatype/nexus3
    ports:
      - "8081:8081"

volumes:
  nexus_data:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: ./nexus-data